spring:
  application:
    name: b-redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      

  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver

server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never
    include-exception: false
